### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by dillibabukadati** [Gowtham95india/way2sms#1]
While entering password nothing is showing, and press enter it's getting exit.

**Comment by fsck-mount** [comment]
You need to have to.txt and the numbers which you want to send inside that file, with "," separated. 

However, added more flexibility in 03aea4186a545ad6358d5e6c8d7e90f5c6846bdf . You just need to run auto.py.

```python
python auto.py
```

**Comment by gwthm-in** [comment]
Not an issue.

**Comment by dillibabukadati** [comment]
Thanks, now it working but small correction that it is not to.py it's
to.txt . And one thing that the message are slecting random but it would be
better if sending own messages rather than sending random messages

On Jun 16, 2017 9:39 PM, "Gowtham Sai" <notifications@github.com> wrote:

You need to have to.py and the numbers which you want to send inside that
file, with "," separated.

However, added more flexibility in 9b6b783
<https://github.com/Gowtham95india/way2sms/commit/9b6b7836466ae0faba75a06e06b853b7e3bc4b09>
. You just need to run auto.py.

python auto.py

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Gowtham95india/way2sms/issues/1#issuecomment-309067324>,
or mute the thread

**Comment by fsck-mount** [comment]
Correct to.py to to.txt. it just a demonstration. You are free to modify it and use it.
